name: Merge CSVs to Tab-separated TXT

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run merge script
        run: python3 WutheringWavesJapaneseDictionary/scripts/merge_csvs.py

      - name: Commit and push merged file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add merged.txt
          git commit -m "Update merged tab-separated TXT" || echo "No changes to commit"
          git push
